const books = [
  {
    id: '1',
    title: 'The White Tiger',
    imageURL: 'https://m.media-amazon.com/images/I/71Nes-1tfPL._AC_UF1000,1000_QL80_.jpg',
    author: 'Aravind Adiga',
    category: 'Fiction',
    description: 'A gripping tale of India’s class struggle told through the eyes of a village boy turned entrepreneur.',
    rating: 4.4,
  },
  {
    id: '2',
    title: 'Midnight’s Children',
    imageURL: 'https://m.media-amazon.com/images/I/81dm0Q2WAdL._AC_UF1000,1000_QL80_.jpg',
    author: 'Salman Rushdie',
    category: 'Fiction',
    description: 'An allegorical novel about India’s transition from British colonialism to independence.',
    rating: 4.2,
  },
  {
    id: '3',
    title: 'Wings of Fire',
    imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe_nW1C0sqU8x2rPHoM-nEkxnOFQ_3JvfWrw&s',
    author: 'A.P.J. Abdul Kalam',
    category: 'Biography',
    description: 'An inspiring autobiography of Dr. A.P.J. Abdul Kalam, the Missile Man of India.',
    rating: 4.7,
  },
  {
    id: '4',
    title: 'Train to Pakistan',
    imageURL: 'https://m.media-amazon.com/images/M/MV5BMDEzOTY3N2MtNDA2NS00YmEzLTljNTItMDcwOWU1OTc0MTc0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    author: 'Khushwant Singh',
    category: 'Historical Fiction',
    description: 'A poignant portrayal of the India-Pakistan partition and its human cost.',
    rating: 4.3,
  },
  {
    id: '5',
    title: 'The Guide',
    imageURL: 'https://m.media-amazon.com/images/I/71GSHBNFdNL._AC_UF1000,1000_QL80_.jpg',
    author: 'R.K. Narayan',
    category: 'Fiction',
    description: 'The story of a tour guide’s transformation into a spiritual guide and eventually a holy man.',
    rating: 4.5,
  },
  {
    id: '6',
    title: 'India After Gandhi',
    imageURL: 'https://images.meesho.com/images/products/439697793/zxabr_512.webp',
    author: 'Ramachandra Guha',
    category: 'Non-Fiction',
    description: 'A comprehensive account of India’s political and social evolution after 1947.',
    rating: 4.6,
  },
  {
    id: '7',
    title: 'Interpreter of Maladies',
    imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR9_d6dXZGEkyt31bNIHSAvFe7_z_LTog7ng&s',
    author: 'Jhumpa Lahiri',
    category: 'Fiction',
    description: 'A Pulitzer Prize-winning collection of short stories about Indian and Indian-American lives.',
    rating: 4.4,
  },
  {
    id: '8',
    title: 'A Suitable Boy',
    imageURL: 'https://m.media-amazon.com/images/I/91kuW6ZbzrL._AC_UF1000,1000_QL80_.jpg',
    author: 'Vikram Seth',
    category: 'Fiction',
    description: 'A sweeping family saga set in post-independence India.',
    rating: 4.1,
  },

  {
    id: '9',
    title: 'The Hobbit',
    imageURL:'https://m.media-amazon.com/images/I/71jD4jMityL._AC_UF1000,1000_QL80_.jpg',
    author: 'J.R.R. Tolkien',
    category: 'Fiction',
    description: 'A fantasy novel about the quest of home-loving hobbit Bilbo Baggins.',
    rating: 4.8,
  },
  {
    id: '10',
    title: 'Sapiens: A Brief History of Humankind',
    imageURL:'https://m.media-amazon.com/images/I/61i4k7DWNFL._AC_UF1000,1000_QL80_.jpg',
    author: 'Yuval Noah Harari',
    category: 'Non-Fiction',
    description: 'Explores how Homo sapiens came to dominate the Earth.',
    rating: 4.6,
  },
  {
    id: '11',
    title: 'Dune',
    imageURL:'https://cdn.kobo.com/book-images/9f8e289a-3834-4f56-99d7-5ef28964e607/1200/1200/False/dune-the-gateway-collection.jpg',
    author: 'Frank Herbert',
    category: 'Sci-Fi',
    description: 'Epic science‑fiction saga set on the desert planet Arrakis.',
    rating: 4.7,
  },
  {
    id: '12',
    title: '1984',
    imageURL:'https://m.media-amazon.com/images/I/51BIA4rraeL._AC_UF1000,1000_QL80_.jpg',
    author: 'George Orwell',
    category: 'Fiction',
    description: 'Dystopian novel set in a totalitarian society ruled by Big Brother.',
    rating: 4.5,
  },
  {
    id: '13',
    title: 'Educated',
    imageURL:'https://m.media-amazon.com/images/I/71QIkI8YetL.jpg',
    author: 'Tara Westover',
    category: 'Biography',
    description: 'A memoir about growing up off the grid and pursuing formal education.',
    rating: 4.4,
  },
  {
    id: '13',
    title: 'Educated',
    imageURL:'https://m.media-amazon.com/images/I/71QIkI8YetL.jpg',
    author: 'Tara Westover',
    category: 'Biography',
    description: 'A memoir about growing up off the grid and pursuing formal education.',
    rating: 4.4,
  },

  
];

export default books;